language: node_js
node_js:
- '6'
before_script:
- npm install -g harp
- chmod +x ./scripts/deploy.sh
script: "./scripts/deploy.sh"
env:
  global:
    secure: Msq0WOpnTBYUa3bm0JAOrAsihuzoVzmgJQ5RZesPAu4VyU5v/SG5OdZJq0TqPJ5mG1jOpTDg+45+wXveD6QW+ahG1RCWufRrxrDr+7WOPm2wOIod0ilTlSMU8Z8xMiCd8WkvuDgcz7er8VJUwmJ9n9NQ0CNf0RebLLwiIsB2uNGKFUx8FG44CpG5LQPKApWbi4ktk0NZ9FqYnL3ufIhKsn9J+c6bKN5UY3Wpf7MKNL1LeUU3SX8J+MaHL3dsV03LjwZymuWCIcgVkjwBSy1De9xhXBn982YACS4p3LH81lQs57911V+Td5USoDFnUt916eMg3U0HFpLDb3pdNvrWmM4f6noKW+vdZ1P5itixIvIpEGukWXYCd3sDLynio47MyzLJSkvK7pTyncZcniIP9vCdNUorXnL8NKo6PmiIQsgxpsaj+LiOyL2YoQ9XR2RbRIjvALbcWTxoh4UW9CtlRBFSzMBb0jNwHiGfH9udcwvTq84NTGBWPI8LzcJvyHKyqsimG1sVpbkkDxsZsU8ixKxhJ0+6sHkITkW7nXL/v3sFrYo+7WPRUalu/BLdcFA4DzNVvHhVpBdjZ09R5R+G3F/eh5EA8PJrftFVtQLVw1S1X0yDyJX5FxV6IyZ7Ruw/435CISxDr5DNTHj++IbqDZbujVh//Kv8MGnmtn2+VV0=
